services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  postgres:
    image: postgres:16-alpine
    container_name: smart-motor-postgres
    environment:
      POSTGRES_DB: smartmotor
      POSTGRES_USER: smartmotor
      POSTGRES_PASSWORD: smartmotor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartmotor -d smartmotor"]
      interval: 5s
      timeout: 3s
      retries: 20


  backend_ingest:
    build:
      context: ../backend
    container_name: smart-motor-backend-ingest
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: "1883"
      MQTT_TOPIC: agro/smart-motor/+/telemetry

      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: smartmotor
      DB_USER: smartmotor
      DB_PASS: smartmotor
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started

    command: ["python", "run.py"]
    restart: unless-stopped

  backend_api:
    build:
      context: ../backend
    container_name: smart-motor-backend-api
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: smartmotor
      DB_USER: smartmotor
      DB_PASS: smartmotor
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["python", "run_api.py"]
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health').read()\""]
      interval: 10s
      timeout: 3s
      retries: 10

    restart: unless-stopped

volumes:
  pgdata:
